# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Update Python Script 
      run: |
        python ./update_readme.py
    - name: Run Update README.md File
      env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PYTHONUNBUFFERED: 1 # Python의 출력 버퍼링이 비활성화되어 print 문의 출력이 실시간으로 Actions 로그에 표시
      run: |
        git add .
        git diff
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m ":smiley: Update README.md file"
        git push
